### PR TITLE
Add PantherX Hotspot

### PR DESCRIPTION
**Pull request by knewspring**

### CODE REVIEW

**Comment by cokes518** [comment]
We won't review this PR until the HW audit is complete.

**Comment by cokes518** [comment]
we'll merge this once MOC approves, a maker account is created, and pantherX is assigned an `id`; in that order.

**Comment by cokes518** [comment]
MOC approved. ready to merge @tyler-whitman @matthewcarlreetz

**Comment by cokes518** [comment]
your maker id is `20`

```"code": 200,
    "data": {
        "id": 20,
        "name": "PantherX",
        "address": "13v9iGhjvQUtVaZXcFFRCEbL1nPR4R8QJowBgMUcaGM2v1aV6mn",
        "locationNonceLimit": 1
    },
    "success": true```

please replace the `id` in your PR and we'll merge!

**Comment by knewspring** [comment]
@cokes518 maker id has been replaced, please merge.  thanks.

**Review by matthewcarlreetz — APPROVED** [review]
Looks good to me!

**Pull request merged**
