### PR TITLE
Add Bobcat Miner 300 to Hotspots App

### PR DESCRIPTION
**Pull request by JackeyTY**

### CODE REVIEW

**Comment by tyler-whitman** [comment]
@JackeyTY Can you pull current changes from main into this.

**Comment by JackeyTY** [comment]
Hi, I don't know how to pull changes from main into pull request. Can I resolve the conflicts manually and then commit merge?

**Comment by JackeyTY** [comment]
I'll fork the current repo again and create another pull request. Close this one.

**Comment by JackeyTY** [comment]
https://github.com/helium/hotspot-app/pull/296

**Pull request closed without merging**
