### PR TITLE
add min height to hotspot settings modals

### LINKED ISSUE #1083: Unable to update height info in Helium app
**Describe the bug**
I am unable to update my height info for my miner Rak HotSpotv2. It's 18m AGL but the Helium app won't let me update it.

**To Reproduce**
I click on the gear icon
I click on "Update Hotspot"
I enter my new height info and when I submit, the page goes blank and hangs there.

I have attached a screen recording for reference,

**Expected behavior**
I should be able to update my height info,

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: iOS 15.1
- App Version: Latest

**Additional context**
Please see attached screen recording. Thank you.

https://user-images.githubusercontent.com/46775664/141655455-e4bd3df8-cdd8-4cf4-ba88-47a2d65fc3a3.mov

.

### PR DESCRIPTION
**Pull request by tyler-whitman**
Hopefully fixes the disappearing hotspots settings modal.

closes #1083

### CODE REVIEW

**Review by matthewcarlreetz — APPROVED** [review]
Interesting. Were you ever able to reproduce?

**Comment by tyler-whitman** [comment]
> Interesting. Were you ever able to reproduce?

No I wasn't.. hoping this fixes it.

**Comment by turribeach** [comment]
@tyler-whitman did you see my videos on #1083? I can still reproduce this on v3.8.5.

**Comment by tyler-whitman** [comment]
> @tyler-whitman did you see my videos on #1083? I can still reproduce this on v3.8.5.

This fix will be out in v3.8.6

**Pull request merged**
