### PR TITLE
update hotspots list for offline hotspots

### LINKED ISSUE #253: Homescreen selecting offline hotspots
When on the home screen and  selecting your "offline hotspots" the list doesn't empty making it look like it's saying all of my hotspots are offline

### LINKED ISSUE #262: Homepage hotspot filter remembering state but clearing filter
When filtering hotspots by "top-performing hotspots" and then minimising the app and then coming back to it, the list is filtered by newest, but the previous selection "top-performing hotspots" is still chosen.

### PR DESCRIPTION
**Pull request by tyler-whitman**
- show "No Hotspots Offline" text for offline filter without offline hotspots
- ensure the list keeps the same filter if you leave the hotspots tab and come back

closes #253 
closes #262

### CODE REVIEW

**Comment by allenan** [comment]
I'm not sure this fully addresses the feedback in #253 but from reading that thread, I'm not sure what the desired UX is exactly. @cokes518 ?

**Comment by cokes518** [comment]
> show "No Hotspots Offline" text for offline filter without offline hotspots

To expand on this, if you apply the offline filter and there is 1 or more Hotspots offline, then we should *only* show those offline hotspots, and none of the online spots.

If you apply the offline filter and there are NO hotspots offline, then we state "No offline hotspots", with a list of online hotspots below. I feel presenting the data this way will prevent people from accidentally selecting the filter then panicking that all their hotspots are gone from their account.

**Comment by tyler-whitman** [comment]
> > show "No Hotspots Offline" text for offline filter without offline hotspots
> 
> To expand on this, if you apply the offline filter and there is 1 or more Hotspots offline, then we should _only_ show those offline hotspots, and none of the online spots.
> 
> If you apply the offline filter and there are NO hotspots offline, then we state "No offline hotspots", with a list of online hotspots below. I feel presenting the data this way will prevent people from accidentally selecting the filter then panicking that all their hotspots are gone from their account.

Ok sounds good. So thats what I was doing except I was not filtering out the online ones in the first case, they were just sorted by offline first. Let me make that change.

**Review by allenan — APPROVED** [review]
this works well and would be fine to merge as is. I'm wondering about the consistency of the experience though. It's a bit inconsistent that when I have offline hotspots, the "Offline Hotspots" filter shows just my offline hotspots, but when I don't have any offline hotspots, I see "No offline hotspots" and then all of my online hotspots under "online hotspots". I guess I'd sort of expect to see maybe just the "no offline hotspots" message maybe larger in the center with an emoji for flair. Just an idea though

**Comment by tyler-whitman** [comment]
> this works well and would be fine to merge as is. I'm wondering about the consistency of the experience though. It's a bit inconsistent that when I have offline hotspots, the "Offline Hotspots" filter shows just my offline hotspots, but when I don't have any offline hotspots, I see "No offline hotspots" and then all of my online hotspots under "online hotspots". I guess I'd sort of expect to see maybe just the "no offline hotspots" message maybe larger in the center with an emoji for flair. Just an idea though

Yeah I was thinking this too, but followed what Coco wanted it to show. I think lets merge it and see what people thing and we can change it if needed

**Pull request merged**
