### PR TITLE
Add McGill Antenna to Helium App

### PR DESCRIPTION
**Pull request by McGillMicrowave**
Please add McGill Microwave antenna to the Helium App in the 'Select Antenna' Section.

Please add the below options:

McGill Antenna (US915/AS923/AU915)
McGill Antenna (EU 868)

Customers can then select their dBi Gain of antenna.

We get asked this from 1000's of customers about what antenna to select, so we would greatly appreciate your help here.

Thank you very much :)

### CODE REVIEW

**Comment by Ryan-Goldstein** [comment]
I don't believe any third party antennas are going to be supported in the app. See https://github.com/helium/hotspot-app/pull/1217#issuecomment-1028452715.

**Comment by McGillMicrowave** [comment]
> I don't believe any third party antennas are going to be supported in the app. See [#1217 (comment)](https://github.com/helium/hotspot-app/pull/1217#issuecomment-1028452715).

Hi Ryan - Many thanks for your response here. I have been in touch with Mark Phillips at helium a few times in the past. Mark kindly let me know to raised this request channel to ensure McGill Antennas are added to the app. McGill Microwave are one of the largest antenna suppliers worldwide for helium, with 20 distributors across the globe. Without disclosing the number of antennas that are currently being used in helium, I'm sure you can sympathise this is a lot of enquiries we are receiving on a daily basis regarding this issue. Can you kindly speak with Mark regarding my request? I'd be very grateful if you can assist here.

**Comment by Ryan-Goldstein** [comment]
> > I don't believe any third party antennas are going to be supported in the app. See [#1217 (comment)](https://github.com/helium/hotspot-app/pull/1217#issuecomment-1028452715).
> 
> Hi Ryan - Many thanks for your response here. I have been in touch with Mark Phillips at helium a few times in the past. Mark kindly let me know to raised this request channel to ensure McGill Antennas are added to the app. McGill Microwave are one of the largest antenna suppliers worldwide for helium, with 20 distributors across the globe. Without disclosing the number of antennas that are currently being used in helium, I'm sure you can sympathise this is a lot of enquiries we are receiving on a daily basis regarding this issue. Can you kindly speak with Mark regarding my request? I'd be very grateful if you can assist here.

I'm not a representative of Helium and have no authority as to what gets merged or not. I'm just providing some feedback based on similar requests I've seen in the past that were rejected. Those include https://github.com/helium/hotspot-app/pull/1217, https://github.com/helium/hotspot-app/pull/1192, and https://github.com/helium/hotspot-app/pull/1079.

**Comment by PharkMillups** [comment]
@McGillMicrowave Whoops. I'm sorry about this. I missed the latest comment (linked above) where the community decided to only include antennas shipped with approved Hotspots. Apologies again for giving you the wrong info.

**Pull request closed without merging**
