### PR TITLE
Feature/import account

### PR DESCRIPTION
**Pull request by matthewcarlreetz**

### CODE REVIEW

**Comment by tyler-whitman** [comment]
I am seeing a cocopod error when trying to install. In using CocoaPods v 1.10.0
```
[!] CocoaPods could not find compatible versions for pod "OneSignal":
  In snapshot (Podfile.lock):
    OneSignal (< 3.0, = 3.0.0-beta3, >= 2.9.3)

  In Podfile:
    OneSignal (< 3.0, >= 2.9.3)

    react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 4.0.0-beta.4, which depends on
      OneSignal (= 3.0.0-beta3)

None of your spec sources contain a spec satisfying the dependencies: `OneSignal (< 3.0, >= 2.9.3), OneSignal (< 3.0, = 3.0.0-beta3, >= 2.9.3), OneSignal (= 3.0.0-beta3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by tyler-whitman** [comment]
> I am seeing a cocoapod error when trying to install. In using CocoaPods v 1.10.0
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "OneSignal":
>   In snapshot (Podfile.lock):
>     OneSignal (< 3.0, = 3.0.0-beta3, >= 2.9.3)
> 
>   In Podfile:
>     OneSignal (< 3.0, >= 2.9.3)
> 
>     react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 4.0.0-beta.4, which depends on
>       OneSignal (= 3.0.0-beta3)
> 
> None of your spec sources contain a spec satisfying the dependencies: `OneSignal (< 3.0, >= 2.9.3), OneSignal (< 3.0, = 3.0.0-beta3, >= 2.9.3), OneSignal (= 3.0.0-beta3)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> ```

Running `pod update` fixes it and updates some of the pods, not sure if we want to do that?

**Comment by matthewcarlreetz** [comment]
> Running `pod update` fixes it and updates some of the pods, not sure if we want to do that?

I think it's because we are using a beta version of OneSignal and you had the main release in your pod cache.

**Comment by allenan** [comment]
as soon as i hit a number on the first pin screen, I get this warning:

**Comment by allenan** [comment]
also right after confirming the pin, I get hit with the notification prompt, which should probably wait until the enable notifications screen

image

**Review by allenan — APPROVED** [review]
works well for me on ios simulator 👍

**Pull request merged**
